# Create lookup table for indicator name mappings

indicator_lookup <- tibble(
  original_name = c(
    "NCD country capacity survey response",
    "Prevalence of obesity among adults, BMI &GreaterEqual; 30 (age-standardized estimate) (%)",
    "Prevalence of overweight among children and adolescents, BMI > +1 standard deviations above the median (crude estimate) (%)",
    "Prevalence of thinness among children and adolescents, BMI < -2 standard deviations below the median (crude estimate) (%)",
    "Prevalence of diabetes, age-standardized",
    "Prevalence of insufficient physical activity among adults aged 18+ years (crude estimate) (%)",
    "Premature deaths due to noncommunicable diseases (NCD) as a proportion of all NCD deaths",
    "Prevalence of insufficient physical activity among adults aged 18+ years (age-standardized estimate) (%)",
    "Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol), by beverage type",
    "Mean HDL cholesterol, crude",
    "Mean Non-HDL cholesterol, crude",
    "Prevalence of obesity among children and adolescents, BMI > +2 standard deviations above the median (crude estimate) (%)",
    "Mean HDL cholesterol, age-standardized",
    "Prevalence of obesity among adults, BMI &GreaterEqual; 30 (crude estimate) (%)",
    "Insufficiently active (crude estimate)",
    "Prevalence of underweight among adults, BMI < 18 (age-standardized estimate) (%)",
    "Prevalence of overweight among adults, BMI &GreaterEqual; 25 (crude estimate) (%)",
    "Mean total cholesterol, crude",
    "Prevalence of underweight among adults, BMI < 18 (crude estimate) (%)",
    "Estimate of current tobacco smoking prevalence (%) (age-standardized rate)",
    "Prevalence of overweight among adults, BMI &GreaterEqual; 25 (age-standardized estimate) (%)",
    "Total NCD Deaths",
    "Crude suicide rates (per 100 000 population)",
    "Prevalence of diabetes, crude",
    "Diabetes treatment coverage, age-standardized",
    "Estimate of current cigarette smoking prevalence (%) (age-standardized rate)",
    "Alcohol, unrecorded per capita (15+) consumption (in litres of pure alcohol), three-year average",
    "Mean Non-HDL cholesterol, age-standardized",
    "Mean total cholesterol, age-standardized",
    "Estimate of current tobacco use prevalence (%) (age-standardized rate)",
    "Probability (%) of dying between age 30 and exact age 70 from any of cardiovascular disease, cancer, diabetes, or chronic respiratory disease",
    "Estimate of current tobacco smoking prevalence (%)",
    "Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol), three-year average",
    "Alcohol, total per capita (15+) consumption (in litres of pure alcohol) (SDG Indicator 3.5.2), three-year average",
    "Estimate of current cigarette smoking prevalence (%)",
    "Estimate of current tobacco use prevalence (%)",
    "Vision and eyecare: Effective refractive error coverage (eREC) (%)",
    "Prevalence of cervical cancer screening among women aged 30-49 years (%)",
    "Monitoring tobacco use and prevention policies",
    "Mean total cholesterol,  age-standardized",
    "Mean total cholesterol,  crude",
    "Prevalence of cervical cancer screening  among women aged 30-49 years (%)"
  ),
  new_name = c(
    "ncd_capacity_survey_resp",
    "std_adult_obesity_preval",
    "youth_overwt_crude_preval",
    "youth_thinness_crude_preval",
    "std_diabetes_preval",
    "insuff_activity_adult_crude_preval",
    "premature_ncd_death_prop",
    "insuff_activity_adult_std_preval",
    "alcohol_recorded_type_ltr_by_type",
    "hdl_chol_crude_mean",
    "nonhdl_chol_crude_mean",
    "youth_obesity_crude_preval",
    "hdl_chol_std_mean",
    "adult_obesity_crude_preval",
    "insuff_activity_crude_rate",
    "adult_underwt_std_preval",
    "adult_overwt_crude_preval",
    "total_chol_crude_mean",
    "adult_underwt_crude_preval",
    "curr_tobacco_smoke_std_preval",
    "adult_overwt_std_preval",
    "ncd_deaths_total",
    "suicide_crude_rate_100k",
    "crude_diabetes_preval",
    "std_diabetes_trtmt_rate",
    "curr_cig_smoke_std_preval",
    "unrec_alcohol_consum_Ltr_3yr_avg",
    "nonhdl_chol_std_mean",
    "total_chol_std_mean",
    "curr_tobacco_use_std_preval",
    "death_risk_30_70_ncd",
    "curr_tobacco_smoke_preval",
    "rec_alcohol_consum_Ltr_3yr_avg",
    "total_alcohol_consum_Ltr_3yr_avg",
    "curr_cig_smoke_preval",
    "curr_tobacco_use_preval",
    "vision_erec_coverage",
    "fem_30_49_cervical_screen",
    "tobacco_policy_monitor",
    "std_mean_total_chol",
    "crude_mean_total_chol",
    "women_30to49_cerv_cancer_screen_preval"
  )
)

write.csv(indicator_lookup,"data/indicators_lookup.csv")
